# Generated by Django 2.1 on 2018-10-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemical_name', models.CharField(max_length=200)),
                ('storage_location', models.CharField(max_length=200)),
                ('msds_ref', models.IntegerField(blank=True)),
                ('id_number', models.IntegerField(blank=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_for_volume', models.CharField(max_length=10)),
                ('surplus', models.BooleanField(default=False)),
                ('storage_code', models.CharField(default='', max_length=50)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('catalog_number', models.CharField(default='', max_length=50)),
                ('order_date', models.DateTimeField(blank=True)),
                ('expiration_date', models.DateTimeField(blank=True, verbose_name='date of expiration')),
                ('comment', models.TextField(default='')),
            ],
        ),
    ]
