# Generated by Django 2.1 on 2018-10-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemicalitem',
            old_name='volume',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='chemicalitem',
            old_name='unit_for_volume',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='chemicalitem',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='chemicalitem',
            name='msds_ref',
        ),
        migrations.RemoveField(
            model_name='chemicalitem',
            name='storage_code',
        ),
        migrations.RemoveField(
            model_name='chemicalitem',
            name='surplus',
        ),
    ]
