# Generated by Django 2.1.2 on 2018-10-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0002_auto_20181019_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalitem',
            name='expiration_date',
            field=models.DateTimeField(null=True, verbose_name='date of expiration'),
        ),
        migrations.AlterField(
            model_name='chemicalitem',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
