# Generated by Django 2.1.2 on 2018-10-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0003_auto_20181022_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalitem',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chemicalitem',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of expiration'),
        ),
        migrations.AlterField(
            model_name='chemicalitem',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
