# Generated by Django 2.1.2 on 2018-10-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical', '0004_auto_20181022_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='date of expiration'),
        ),
        migrations.AlterField(
            model_name='chemicalitem',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
